#! /usr/bin/python

import sys
import os

try:
  import advene.core.config as config
except ImportError:
  # The package was not installed in a standard place (or PYTHONPATH
  # is not correctly set). Try to find if we are in a development tree.
  (maindir, subdir) = os.path.split(os.path.dirname(os.path.abspath(sys.argv[0])))
  if subdir == 'bin' and  os.path.exists(os.sep.join((maindir, "setup.py"))):
    # Chances are that we were in a development tree...
    libpath=os.sep.join((maindir, "lib"))
    print "You seem to have a development tree at:\n%s." % libpath
    sys.path.insert (0, libpath)
    
    import advene.core.config as config
    # We override any modification that could have been made in
    # .advenerc. Rationale: if the .advenerc was really correct, it
    # would have set the correct package path in the first place.
    print "Overriding 'resources' and 'web' config paths"
    config.data.path['resources']=os.path.sep.join((maindir, 'share'))
    config.data.path['web']=os.path.sep.join((maindir, 'share', 'web'))

    # Check for MediaControl.so
    if not os.path.exists(config.data.typelib):
      print """Error: cannot find the typelib file (%s) to control the player.
      Check that the vlc-plugin-corba is correctly installed.
      Aborting.""" % config.data.typelib
      sys.exit(1)
  else:
    print """Cannot guess a valid directory.
    Please check your installation or set the PYTHONPATH environment variable."""
    sys.exit(1)    

import advene.gui.main

if __name__ == '__main__':
  # FIXME: remove once the win32 support is correct
  if config.data.os != "win32" and not os.path.exists(config.data.typelib):
    print """The %s file does not exist.
    Either the VLC plugin is not installed or it is badly configured.
    Check your .advenerc file.""" % config.data.typelib
    sys.exit(1)
    
  gladefile=config.data.advenefile (config.data.gladefilename)
  if not os.path.exists(gladefile):
    print """The %s file does not exist.
    Either the Advene software is not installed or it is badly configured.
    Check your .advenerc file.""" % gladefile
    sys.exit(1)

  v = advene.gui.main.DVDControl ()
  try:
    v.main (sys.argv[1:])
  except Exception, e:
    print _("Got exception %s. Stopping services...") % str(e)
    v.on_exit ()
    print _("*** Exception ***")
    import code
    e, v, tb = sys.exc_info()
    code.traceback.print_exception (e, v, tb)
